# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import uzewiki.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uzewiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.SlugField(help_text='Internal name for the asset'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, help_text='Page content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If locked, can only be edited by wiki admin'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=uzewiki.fields.WikiSlugField(help_text='Slug for the page', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='Title of the page', max_length=255),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='description',
            field=models.TextField(blank=True, help_text='Description of wiki'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='perm_edit',
            field=models.IntegerField(choices=[(3, 'Superusers only'), (2, 'Staff only'), (1, 'All users'), (0, 'Public')], default=3, help_text='Default edit permissions', verbose_name='Edit permission'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='perm_read',
            field=models.IntegerField(choices=[(3, 'Superusers only'), (2, 'Staff only'), (1, 'All users'), (0, 'Public')], default=3, help_text='Default read permissions', verbose_name='Read permission'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='slug',
            field=models.SlugField(help_text='Slug for the wiki', unique=True),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='title',
            field=models.CharField(help_text='Title of the wiki', max_length=255),
        ),
        migrations.AlterField(
            model_name='wikipermissions',
            name='can_edit',
            field=models.BooleanField(default=True, help_text='User can edit the wiki'),
        ),
        migrations.AlterField(
            model_name='wikipermissions',
            name='can_read',
            field=models.BooleanField(default=True, help_text='User can read the wiki'),
        ),
    ]
