# Generated by Django 3.2.14 on 2023-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerwiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='depth',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
