# Generated by Django 4.2.17 on 2024-12-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("powerwiki", "0003_set_depth"),
    ]

    operations = [
        migrations.AddField(
            model_name="wiki",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Archived wikis are available but hidden from normal use",
            ),
        ),
        migrations.AddField(
            model_name="wiki",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
